arb-dir: lib/core/localizations/arb
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localizations
preferred-supported-locales:
  - en
  - fa
