name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/fonts/
    - assets/lottie/
  
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/core/utils/gen/
  integrations:
    flutter_svg: true